namePrefix: capv-

commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-vsphere"

bases:
  - ../../config/crd
  - ../../config/webhook # Disable this if you're not using the webhook functionality.

patchesJson6902:
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: haproxyloadbalancers.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vsphereclusters.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vspheremachines.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vspheremachinetemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vspherevms.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
