name: Release
run-name: Release for Cluster API Vsphere ${{ github.event.inputs.release_version }}
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Cluster API Version to Build'
        required: true
        default: '0.0.0'
jobs:
  builder:
    # edge-runner machine group is a bunch of machines in US Datacenter
    runs-on: ubuntu-latest
    # Initialize all secrets required for the job
    # Ensure that the credentials are provided as encrypted secrets
    env:
      SPECTRO_VERSION: ${{ github.event.inputs.release_version }}
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@v3
      - name: Build Image
        env:
          DEV_REGISTRY: gcr.io/spectro-images-public/release/cluster-api-vsphere
        run: |
          make docker-build
      - name: Build Image - FIPS Mode 
        env: 
          FIPS_ENABLE: yes
          DEV_REGISTRY: gcr.io/spectro-images-public/release-fips/cluster-api-vsphere
        run: |
          make docker-build
